In [2]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.optimize as opt

In [24]:
xs = np.array([0, 1, 2, 3, 4])
ys = np.array([0, 1, 1, 2, 2])

s = xs.size
A = np.zeros([2,2])
b = np.zeros([2])

for i in range(2):
    for k in range (s):
        b[i] += xs[k] ** i * ys[k]
    for j in range (2):
        for k in range (s):
            A[i, j] += xs[k]**(j + i)

np.linalg.solve(A,b)

array([0.2, 0.5])

In [74]:
def least_squares_matrix(x, y, n):
    s = x.size
    A = np.zeros([n+1, n+1])
    b = np.zeros([n+1])
    for i in range (n+1):
        for k in range (s):
            b[i] += x[k]**i * y[k]
        for j in range(n+1):
            for k in range (s):
                A[i,j] += x[k] ** (i+j)
    return (np.linalg.solve(A, b))       

In [76]:
#zad 7.2
import pandas as pd
df = pd.read_csv('CO_2_data.csv')
year = df['year']
co2 = df['co2']

least_squares_matrix(year, co2, 1)

array([-8.33280314e+02,  4.30363125e-01])

In [83]:
#zad 7.3
df = pd.read_csv('wind_turbine_data_sample.csv')
wind = df['wind speed']
power = df['power output']

least_squares_matrix(wind, power, 3)

array([ 2787.95787836, -1334.75406706,   205.91711217,    -7.59606065])

In [90]:
#zad 7.4
df = pd.read_csv('amazon_sales_net_revenue.csv')
year = df['year']
revenue = df['revenue']

least_squares_matrix(year, revenue, 1)

array([-4.58770519e+04,  2.28562745e+01])

In [97]:
#4
from sympy import symbols, diff, solve, Eq
x,y = symbols('x, y')

def f(x, y):
    return (x - y - 1)**2 + (x + y -1)**2 + (x - y + 1)**2 + (x + y + 1)**2

sol = solve([Eq(diff(f(x,y), x), 0),
             Eq(diff(f(x,y), y), 0)])
sol

{x: 0, y: 0}

In [99]:
#5
x,y,z = symbols('x, y, z')

phi = (2*x + y + z - 1)**2 + (x + 2*y + z - 2)**2 + (x + 3*y + z - 3)**2 + (x - 4*y + z - 4)**2 + (x + 5*y + z - 4)**2

sol = solve([Eq(diff(phi, x), 0),
             Eq(diff(phi, y), 0),
             Eq(diff(phi, z), 0)])

sol

{x: -41/18, y: -1/18, z: 101/18}