# Метод на най-малките квадрати - Част 2. 
## Векторно-матрична форма. Решаване на преопределени системи от уравнения.

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.optimize as opt

### Задача 1

Като се използва векторно-мартричната форма на метода на май-малките квадрати за приближаване с алгебрични полиноми, 
Да се намери линейна функция, която приближава данните от таблицата

|x| 0 | 1 | 2 | 3 | 4
|---|---|---|---|---|---|
|y|0|1|1|2|2|

In [4]:
x = np.array([0, 1, 2, 3, 4])
y = np.array([0, 1, 1, 2, 2])

s = x.size
A = np.zeros([2, 2])
b = np.zeros([2])
for i in range(2):
    for k in range(s):
        b[i] += x[k] ** i * y[k]
    for j in range(2):
        for k in range(s):
            A[i, j] += x[k] ** (i + j)

print(A)
print(b)
np.linalg.solve(A, b)

[[ 5. 10.]
 [10. 30.]]
[ 6. 17.]


array([0.2, 0.5])

### Задача 2

Да се напише функция *least_squares_matrix(x, y, n)*, която приближава точките с коориднати $\{x_i,y_i\}, i = 0,\dots s $ с алгебричен полином от степен $n$ по метода на най-малките квадрати, записан във векторно-матрична форма, където *x* и *y* са списъци с реални числа.

In [6]:
def least_squares_matrix(x, y, n):
    s = x.size
    A = np.zeros([n + 1, n + 1])
    b = np.zeros([n + 1])
    for i in range(n + 1):
        for k in range(s):
            b[i] += x[k] ** i * y[k]
        for j in range(n + 1):
            for k in range(s):
                A[i, j] += x[k] ** (i + j)
    return(np.linalg.solve(A, b))

### Задача 3

Като се използва написаната в Задача 2 функция, да се решат Задачи 2, 3 и 4 от Упражнение 7.

In [8]:
# Задача 2 - въглероден диоксид
import pandas as pd
df = pd.read_csv('CO_2_data.csv')
df.head()
years = df.loc[:, "year"]
co2 = df.loc[:, "co2"]

least_squares_matrix(years, co2, 1)

array([-8.33280314e+02,  4.30363125e-01])

In [9]:
# Задача 3 - вятърна енергия
df = pd.read_csv('wind_turbine_data_sample.csv')
df.head()
wind_speed = df.loc[:, "wind speed"]
power_output = df.loc[:, "power output"]

least_squares_matrix(wind_speed, power_output, 3)

array([ 2787.9578783 , -1334.75406703,   205.91711217,    -7.59606065])

In [10]:
# Задача 4 - Amazon.com
df = pd.read_csv('amazon_sales_net_revenue.csv')
years = df.loc[:, "year"]
revenue = df.loc[:, "revenue"]
revenue_log = np.log(revenue)

least_squares_matrix(years, revenue_log, 1)

array([-4.97459710e+02,  2.49215934e-01])

### Задача 4
Да се реши преопределената система

$$
\left|
\begin{aligned}
x-y&=1\\
x+y&=1\\
x+y&=-1\\
x-y&=-1
\end{aligned}
\right.
$$

In [12]:
from sympy import symbols, diff, solve, Eq
x, y = symbols('x y')

def objective(x, y):
    return (x - y - 1) ** 2 + (x + y - 1) ** 2 + (x + y + 1) ** 2 + (x - y + 1) ** 2

equations = [Eq(diff(objective(x, y), x), 0),
             Eq(diff(objective(x, y), y), 0)]

solve(equations)

{x: 0, y: 0}

### Задача 5

Да се реши преопределената система

$$
\left|
\begin{aligned}
2 x + y + z &= 1\\
x + 2y + z&=2\\
x + 3y + z &= 3\\
x - 4y + z &= 4\\
x + 5y + z &= 4
\end{aligned}
\right.
$$

In [44]:
from sympy import symbols, diff, solve, Eq

x, y, z = symbols('x, y, z')

phi = (2*x + y + z - 1) ** 2 + (x + 2*y +z - 2) ** 2 + (x + 3*y+z - 3) ** 2 + (x - 4* y + z - 4) ** 2 + (x + 5* y+z -4) **2
phi

(x - 4*y + z - 4)**2 + (x + 2*y + z - 2)**2 + (x + 3*y + z - 3)**2 + (x + 5*y + z - 4)**2 + (2*x + y + z - 1)**2

In [46]:
solve([Eq(diff(phi, x), 0),
 Eq(diff(phi, y), 0),
 Eq(diff(phi, z), 0)])

{x: -41/18, y: -1/18, z: 101/18}